title: Sam Deans Projects
author: Sam Deans
email: samdeans75@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 A blog with links to my projects.

# social links
github_username:  @sdeans0

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
